thulab/IginX

core/src/main/java/cn/edu/tsinghua/iginx/policy/IPlanSplitter.java
core/src/main/java/cn/edu/tsinghua/iginx/policy/NaivePlanSplitter.java

- 存在问题：按照原来的随机的分片选择策略，如果写入之后立即查询，而且选到了副分片，那么会出现查询结果不正确的情况。
- 解决方案：现暂时将查询改成只查主分片，后面再做进一步修改。

Change fragment selection policy temporarily

---

iotdb/src/main/java/cn/edu/tsinghua/iginx/iotdb/IoTDBPlanExecutor.java
iotdb/src/main/java/cn/edu/tsinghua/iginx/iotdb/query/entity/IoTDBQueryExecuteDataSet.java

- 特性改动：将IoTDB查询结果集列名的前缀root.去掉。
- 改动原因：这是IoTDB的特性，不应该暴露给IginX的用户。

Modify query dataset display format

---

core/src/main/java/cn/edu/tsinghua/iginx/conf/Constants.java
core/src/main/java/cn/edu/tsinghua/iginx/session/Session.java
core/src/main/java/cn/edu/tsinghua/iginx/statistics/QueryStatisticsCollector.java
core/src/main/java/cn/edu/tsinghua/iginx/utils/RpcUtils.java

support request redirect

---

core/src/main/java/cn/edu/tsinghua/iginx/combine/aggregate/AggregateCombiner.java
core/src/main/java/cn/edu/tsinghua/iginx/combine/querydata/QueryDataSetCombiner.java
core/src/main/java/cn/edu/tsinghua/iginx/plan/InsertColumnRecordsPlan.java
core/src/main/java/cn/edu/tsinghua/iginx/plan/InsertRecordsPlan.java
core/src/main/java/cn/edu/tsinghua/iginx/plan/InsertRowRecordsPlan.java
core/src/main/java/cn/edu/tsinghua/iginx/session/Session.java
core/src/main/java/cn/edu/tsinghua/iginx/session/SessionQueryDataSet.java
core/src/main/java/cn/edu/tsinghua/iginx/split/SimplePlanGenerator.java
core/src/main/java/cn/edu/tsinghua/iginx/utils/ByteUtils.java
example/src/main/java/cn/edu/tsinghua/iginx/session/IoTDBSessionExample.java
iotdb/src/main/java/cn/edu/tsinghua/iginx/iotdb/IoTDBPlanExecutor.java
thrift/src/main/proto/rpc.thrift

- 特性改动：insertColumnRecords接口支持写入空值。
- 改动原因：与insertRowRecords接口保持一致。

Enable insertColumnRecords to carry null values

---

core/src/main/java/cn/edu/tsinghua/iginx/combine/aggregate/AggregateCombiner.java
example/src/main/java/cn/edu/tsinghua/iginx/session/InfluxDBSessionExample.java
example/src/main/java/cn/edu/tsinghua/iginx/session/IoTDBSessionExample.java
influxdb/src/main/java/cn/edu/tsinghua/iginx/influxdb/InfluxDBPlanExecutor.java
influxdb/src/main/java/cn/edu/tsinghua/iginx/influxdb/query/entity/InfluxDBQueryExecuteDataSet.java

Add downsample query for influxdb

---

client/src/main/java/cn/edu/tsinghua/iginx/client/IginxClient.java
core/src/main/java/cn/edu/tsinghua/iginx/cluster/IginxWorker.java
core/src/main/java/cn/edu/tsinghua/iginx/core/db/StorageEngine.java
influxdb/src/main/java/cn/edu/tsinghua/iginx/influxdb/InfluxDBPlanExecutor.java
iotdb/src/main/java/cn/edu/tsinghua/iginx/iotdb/IoTDBPlanExecutor.java

Enable to add InfluxDB instances

---

conf/config.properties
core/src/main/java/cn/edu/tsinghua/iginx/conf/Config.java
core/src/main/java/cn/edu/tsinghua/iginx/conf/ConfigDescriptor.java
iotdb/src/main/java/cn/edu/tsinghua/iginx/iotdb/IoTDBPlanExecutor.java

- 底层实现改动：将IoTDB对接层中用于写入的session池和用于查询的session池合并。

Modify iotdb session pool

---

client/src/main/java/cn/edu/tsinghua/iginx/client/IginxClient.java
core/src/main/java/cn/edu/tsinghua/iginx/session/Session.java

Reverts thulab/IginX#62
Surprisingly, none of the functions are correct!!!!!!!
@humanfy

Revert "Add three more client functions"

---

client/src/main/java/cn/edu/tsinghua/iginx/client/IginxClient.java
core/src/main/java/cn/edu/tsinghua/iginx/session/Session.java

Revert "Revert "Add three more client functions""

---

client/src/main/java/cn/edu/tsinghua/iginx/client/IginxClient.java
core/src/main/java/cn/edu/tsinghua/iginx/session/Session.java

Revert "Revert "Revert "Add three more client functions"""

---

client/src/main/java/cn/edu/tsinghua/iginx/client/IginxClient.java
core/src/main/java/cn/edu/tsinghua/iginx/session/Session.java

Revert "Revert "Revert "Revert "Add three more client functions""""

---

conf/config.properties
core/src/main/java/cn/edu/tsinghua/iginx/cluster/IginxWorker.java
core/src/main/java/cn/edu/tsinghua/iginx/conf/Config.java
core/src/main/java/cn/edu/tsinghua/iginx/conf/ConfigDescriptor.java
core/src/main/java/cn/edu/tsinghua/iginx/metadata/AbstractMetaManager.java
core/src/main/java/cn/edu/tsinghua/iginx/metadata/DefaultMetaManager.java
core/src/main/java/cn/edu/tsinghua/iginx/metadata/entity/StorageEngineMeta.java
core/src/main/java/cn/edu/tsinghua/iginx/policy/NaivePlanSplitter.java
core/src/main/java/cn/edu/tsinghua/iginx/policy/NativePolicy.java

- 修复了时存在并发访问的情况下数据分片会被重复创建的问题；
- 针对存在乱序数据的情况下新增分片缓冲边界

fix bug of reallowcate and dev margin

---

docs/quick start.md

modify quick start.md

---

antlr/pom.xml
antlr/src/main/antlr4/cn/edu/tsinghua/iginx/sql/Sql.g4
client/src/main/java/cn/edu/tsinghua/iginx/client/IginxClient.java
core/pom.xml
core/src/main/java/cn/edu/tsinghua/iginx/cluster/IginxWorker.java
core/src/main/java/cn/edu/tsinghua/iginx/exceptions/SQLParserException.java
core/src/main/java/cn/edu/tsinghua/iginx/session/Session.java
core/src/main/java/cn/edu/tsinghua/iginx/session/SessionExecuteSqlResult.java
core/src/main/java/cn/edu/tsinghua/iginx/sql/IginXSqlVisitor.java
core/src/main/java/cn/edu/tsinghua/iginx/sql/SQLConstant.java
core/src/main/java/cn/edu/tsinghua/iginx/sql/operator/AddStorageEngineOperator.java
core/src/main/java/cn/edu/tsinghua/iginx/sql/operator/DeleteOperator.java
core/src/main/java/cn/edu/tsinghua/iginx/sql/operator/InsertOperator.java
core/src/main/java/cn/edu/tsinghua/iginx/sql/operator/Operator.java
core/src/main/java/cn/edu/tsinghua/iginx/sql/operator/SelectOperator.java
core/src/main/java/cn/edu/tsinghua/iginx/sql/operator/ShowReplicationOperator.java
core/src/main/java/cn/edu/tsinghua/iginx/utils/SortUtils.java
core/src/main/java/cn/edu/tsinghua/iginx/utils/TimeUtils.java
core/src/test/java/cn/edu/tsinghua/iginx/sql/ParseTest.java
example/src/main/java/cn/edu/tsinghua/iginx/session/SessionExecuteExample.java
pom.xml
thrift/src/main/proto/rpc.thrift

1. add SQL parser and execute support
2. add client sql support
3. add some tests

add SQL support

---

antlr/src/main/antlr4/cn/edu/tsinghua/iginx/sql/Sql.g4
core/src/main/java/cn/edu/tsinghua/iginx/cluster/IginxWorker.java
core/src/main/java/cn/edu/tsinghua/iginx/exceptions/SQLParserException.java
core/src/main/java/cn/edu/tsinghua/iginx/sql/IginXSqlVisitor.java
core/src/main/java/cn/edu/tsinghua/iginx/sql/SQLConstant.java
core/src/main/java/cn/edu/tsinghua/iginx/sql/operator/InsertOperator.java
core/src/main/java/cn/edu/tsinghua/iginx/sql/operator/SelectOperator.java
core/src/test/java/cn/edu/tsinghua/iginx/sql/ParseTest.java
example/src/main/java/cn/edu/tsinghua/iginx/session/SQLSessionExample.java
iotdb/src/main/java/cn/edu/tsinghua/iginx/iotdb/IoTDBPlanExecutor.java
jdbc/src/test/java/ExampleTest.java
test/src/test/java/cn/edu/tsinghua/iginx/integration/BaseSessionIT.java

* from clause only support one prefixPath for now
* support four types of time range
* change storage engine extra format
* add more error msg in client

modeify sql spec

---

antlr/src/main/antlr4/cn/edu/tsinghua/iginx/sql/Sql.g4
client/src/main/java/cn/edu/tsinghua/iginx/client/IginxClient.java
core/src/main/java/cn/edu/tsinghua/iginx/cluster/IginxWorker.java
core/src/main/java/cn/edu/tsinghua/iginx/exceptions/SQLParserException.java
core/src/main/java/cn/edu/tsinghua/iginx/sql/IginXSqlVisitor.java
core/src/main/java/cn/edu/tsinghua/iginx/sql/operator/Operator.java
core/src/main/java/cn/edu/tsinghua/iginx/sql/operator/SelectOperator.java
core/src/main/java/cn/edu/tsinghua/iginx/sql/operator/ShowTimeSeriesOperator.java
core/src/test/java/cn/edu/tsinghua/iginx/sql/ParseTest.java
pom.xml
session/src/main/java/cn/edu/tsinghua/iginx/session/SessionExecuteSqlResult.java
thrift/src/main/proto/rpc.thrift

* support limit
* support show time series
* opt output data set format
* add IginX logo in client

add SQL type

---

influxdb/src/main/java/cn/edu/tsinghua/iginx/influxdb/InfluxDBPlanExecutor.java
test/src/test/java/cn/edu/tsinghua/iginx/integration/BaseSessionIT.java

Fix a bug in insertColumnRecords and insertRowRecords in InfluxDB

fix insertColumn/RowRecords in InfluxDB

---

core/src/main/java/cn/edu/tsinghua/iginx/engine/logical/optimizer/FilterPushDownOptimizer.java
core/src/main/java/cn/edu/tsinghua/iginx/engine/logical/optimizer/LogicalOptimizerManager.java
core/src/main/java/cn/edu/tsinghua/iginx/engine/logical/optimizer/RemoveNotOptimizer.java
core/src/main/java/cn/edu/tsinghua/iginx/engine/logical/utils/ExprUtils.java
core/src/main/java/cn/edu/tsinghua/iginx/engine/shared/operator/AbstractBinaryOperator.java
core/src/main/java/cn/edu/tsinghua/iginx/engine/shared/operator/AbstractMultipleOperator.java
core/src/main/java/cn/edu/tsinghua/iginx/engine/shared/operator/AbstractUnaryOperator.java
core/src/main/java/cn/edu/tsinghua/iginx/engine/shared/operator/BinaryOperator.java
core/src/main/java/cn/edu/tsinghua/iginx/engine/shared/operator/MultipleOperator.java
core/src/main/java/cn/edu/tsinghua/iginx/engine/shared/operator/UnaryOperator.java
core/src/main/java/cn/edu/tsinghua/iginx/engine/shared/operator/filter/BoolFilter.java
core/src/main/java/cn/edu/tsinghua/iginx/engine/shared/operator/filter/FilterType.java
core/src/main/java/cn/edu/tsinghua/iginx/rest/query/QueryParser.java
core/src/test/java/cn/edu/tsinghua/iginx/sql/ExprUtilsTest.java

*dev filter push down optimizer
*fix annotation in rest

filter push down

---

docs/quickStarts/IginXBySource.md
docs/quickStarts/IginXManual.md

Some of the versions for all apache files and downloads are out of date. This one I was able to confirm so I have updated it.

Updated SNAPSHOT version from 0.4.0 to 0.5.0

---

.gitignore
docs/quickStarts/IginXBySource-EnglishVersion.md

No files changed, cloned the repo from the beginning

Opening PR with SSH key

---

docs/quickStarts/EnglishManuals/IginXByDocker-EnglishVersion.md
docs/quickStarts/EnglishManuals/IginXBySource-EnglishVersion.md

Adding IginXBySource with corrections, and uploading new translated manual: IginXByDocker translation.

Corrected IginXBySource.md, Added New: IginXByDocker.md

---

.github/workflows/system-test.yml
docs/Transform_Function_List.md
python_scripts/transformer_bottom.py
python_scripts/transformer_distinct.py
python_scripts/transformer_mean.py
python_scripts/transformer_spread.py

This is the complete .md file. There is a list of functions followed by the expanded list with the descriptions for each in English and Chinese.

Transform function list

---

core/src/main/java/cn/edu/tsinghua/iginx/transform/data/FileAppendWriter.java
core/src/main/java/cn/edu/tsinghua/iginx/transform/data/IginXWriter.java
core/src/main/java/cn/edu/tsinghua/iginx/transform/exec/JobValidationChecker.java
core/src/main/java/cn/edu/tsinghua/iginx/transform/exec/StreamStageRunner.java
core/src/main/java/cn/edu/tsinghua/iginx/transform/pojo/IginXTask.java
core/src/main/java/cn/edu/tsinghua/iginx/transform/pojo/Job.java
example/src/main/java/cn/edu/tsinghua/iginx/session/TransformCompare.java
example/src/main/java/cn/edu/tsinghua/iginx/session/TransformExample.java
example/src/main/resources/TransformJobExample.yaml
session/src/main/java/cn/edu/tsinghua/iginx/session/Session.java
session/src/main/java/cn/edu/tsinghua/iginx/session_v2/domain/Task.java
session/src/main/java/cn/edu/tsinghua/iginx/session_v2/domain/Transform.java
session/src/main/java/cn/edu/tsinghua/iginx/session_v2/internal/TransformClientImpl.java
shared/src/main/java/cn/edu/tsinghua/iginx/utils/JobFromYAML.java
shared/src/main/java/cn/edu/tsinghua/iginx/utils/TaskFromYAML.java
test/src/test/java/cn/edu/tsinghua/iginx/integration/UDFIT.java
thrift/src/main/proto/rpc.thrift

1. support show time series
2. support multiple SQL statement
3. support export name list

feat: enhance transform

---

dataSources/iotdb11/src/main/java/cn/edu/tsinghua/iginx/iotdb/tools/DataViewWrapper.java
dataSources/iotdb11/src/main/java/cn/edu/tsinghua/iginx/iotdb/tools/TagKVUtils.java
dataSources/iotdb12/src/main/java/cn/edu/tsinghua/iginx/iotdb/tools/DataViewWrapper.java
dataSources/iotdb12/src/main/java/cn/edu/tsinghua/iginx/iotdb/tools/TagKVUtils.java
shared/src/main/java/cn/edu/tsinghua/iginx/utils/TagKVUtils.java

https://oxlh5mrwi0.feishu.cn/docx/doxcnvSi9b74iMmICu9GgMoR2g9

fix tagkv prefix bug

---

antlr/src/main/antlr4/cn/edu/tsinghua/iginx/sql/Sql.g4
core/src/main/java/cn/edu/tsinghua/iginx/engine/StatementExecutor.java
core/src/main/java/cn/edu/tsinghua/iginx/engine/logical/generator/ShowTimeSeriesGenerator.java
core/src/main/java/cn/edu/tsinghua/iginx/engine/physical/storage/execute/StoragePhysicalTaskExecutor.java
core/src/main/java/cn/edu/tsinghua/iginx/engine/physical/storage/utils/TagKVUtils.java
core/src/main/java/cn/edu/tsinghua/iginx/engine/shared/operator/ShowTimeSeries.java
core/src/main/java/cn/edu/tsinghua/iginx/engine/shared/operator/tag/TagFilterType.java
core/src/main/java/cn/edu/tsinghua/iginx/engine/shared/operator/tag/WithoutTagFilter.java
core/src/main/java/cn/edu/tsinghua/iginx/sql/IginXSqlVisitor.java
core/src/main/java/cn/edu/tsinghua/iginx/sql/statement/DeleteStatement.java
core/src/main/java/cn/edu/tsinghua/iginx/sql/statement/DeleteTimeSeriesStatement.java
core/src/main/java/cn/edu/tsinghua/iginx/sql/statement/ShowTimeSeriesStatement.java
core/src/test/java/cn/edu/tsinghua/iginx/sql/ParseTest.java
dataSources/iotdb11/src/main/java/cn/edu/tsinghua/iginx/iotdb/IoTDBStorage.java
dataSources/iotdb11/src/main/java/cn/edu/tsinghua/iginx/iotdb/tools/TagKVUtils.java
dataSources/iotdb12/src/main/java/cn/edu/tsinghua/iginx/iotdb/IoTDBStorage.java
dataSources/iotdb12/src/main/java/cn/edu/tsinghua/iginx/iotdb/tools/TagKVUtils.java
example/src/main/java/cn/edu/tsinghua/iginx/session/SQLSessionExample.java
jdbc/src/test/java/BatchTest.java
test/src/test/java/cn/edu/tsinghua/iginx/integration/SQLSessionIT.java
test/src/test/java/cn/edu/tsinghua/iginx/integration/TagIT.java
test/src/test/java/cn/edu/tsinghua/iginx/integration/history/IoTDBHistoryDataCapacityExpansionIT.java

1. support date format like '2022.08.29 19:22:23' and '2022.08.29T19:22:23'
2. change add storageEngine statement's ip from number to str
3. support query without tag
4. support show TS with limit and offset
5. support delete time series with tag filter

feat: task from 20220829

---

client/src/main/java/cn/edu/tsinghua/iginx/client/IginxClient.java
conf/config.properties
core/pom.xml
core/src/main/java/cn/edu/tsinghua/iginx/IginxWorker.java
core/src/main/java/cn/edu/tsinghua/iginx/conf/Config.java
core/src/main/java/cn/edu/tsinghua/iginx/conf/ConfigDescriptor.java
core/src/main/java/cn/edu/tsinghua/iginx/engine/ContextBuilder.java
core/src/main/java/cn/edu/tsinghua/iginx/engine/physical/memory/execute/utils/FilterUtils.java
core/src/main/java/cn/edu/tsinghua/iginx/engine/shared/data/read/Header.java
core/src/main/java/cn/edu/tsinghua/iginx/engine/shared/data/read/Row.java
maven-repo/cn/edu/tsinghua/iginx-shared/0.5.0/iginx-shared-0.5.0.pom
shared/pom.xml
shared/src/main/java/cn/edu/tsinghua/iginx/utils/StringUtils.java
test/src/test/java/cn/edu/tsinghua/iginx/integration/RestIT.java
test/src/test/java/cn/edu/tsinghua/iginx/integration/SQLSessionIT.java
test/src/test/resources/restIT/insert.json
test/src/test/resources/restIT/testDelete.json
test/src/test/resources/restIT/testQueryAvg.json
test/src/test/resources/restIT/testQueryCount.json
test/src/test/resources/restIT/testQueryFirst.json
test/src/test/resources/restIT/testQueryLast.json
test/src/test/resources/restIT/testQueryMax.json
test/src/test/resources/restIT/testQueryMin.json
test/src/test/resources/restIT/testQueryOneTagWrong.json
test/src/test/resources/restIT/testQuerySum.json
test/src/test/resources/restIT/testQueryWithTags.json
test/src/test/resources/restIT/testQueryWithoutTags.json
test/src/test/resources/restIT/testQueryWrongTags.json
test/src/test/resources/restIT/testQueryWrongTime.json
zeppelin-interpreter/src/main/java/org/apache/zeppelin/iginx/IginxInterpreter.java

1. support * compare like a.*.b > 10
2. forbid single sub-path insert, like aaa is illegal and aaa.bbb is legal
3. add special path tests
4. upgrade SnakeYAML to 1.32
5. remove set time unit

task from 20220919

---

core/src/main/java/cn/edu/tsinghua/iginx/engine/physical/memory/execute/naive/NaiveOperatorMemoryExecutor.java
core/src/main/java/cn/edu/tsinghua/iginx/engine/physical/memory/execute/utils/TableUtils.java

delete timestamp column in final join result

fix some bugs

---

core/src/main/java/cn/edu/tsinghua/iginx/engine/physical/memory/execute/naive/NaiveOperatorMemoryExecutor.java
core/src/main/java/cn/edu/tsinghua/iginx/engine/physical/memory/execute/utils/FilterUtils.java
core/src/main/java/cn/edu/tsinghua/iginx/engine/physical/memory/execute/utils/RowUtils.java
core/src/main/java/cn/edu/tsinghua/iginx/engine/physical/memory/execute/utils/TableUtils.java
core/src/test/java/cn/edu/tsinghua/iginx/engine/physical/memory/execute/AbstractOperatorMemoryExecutorTest.java

add sorted merge join;
add many-to-many join tests;
fix a bug in natural outer join

sorted merge join

---

antlr/src/main/antlr4/cn/edu/tsinghua/iginx/sql/Sql.g4
core/src/main/java/cn/edu/tsinghua/iginx/engine/logical/generator/QueryGenerator.java
core/src/main/java/cn/edu/tsinghua/iginx/engine/physical/memory/execute/naive/NaiveOperatorMemoryExecutor.java
core/src/main/java/cn/edu/tsinghua/iginx/engine/physical/memory/execute/stream/CrossJoinLazyStream.java
core/src/main/java/cn/edu/tsinghua/iginx/engine/physical/memory/execute/stream/HashInnerJoinLazyStream.java
core/src/main/java/cn/edu/tsinghua/iginx/engine/physical/memory/execute/stream/HashOuterJoinLazyStream.java
core/src/main/java/cn/edu/tsinghua/iginx/engine/physical/memory/execute/stream/NestedLoopInnerJoinLazyStream.java
core/src/main/java/cn/edu/tsinghua/iginx/engine/physical/memory/execute/stream/NestedLoopOuterJoinLazyStream.java
core/src/main/java/cn/edu/tsinghua/iginx/engine/physical/memory/execute/stream/SortedMergeInnerJoinLazyStream.java
core/src/main/java/cn/edu/tsinghua/iginx/engine/physical/memory/execute/stream/SortedMergeOuterJoinLazyStream.java
core/src/main/java/cn/edu/tsinghua/iginx/engine/physical/memory/execute/stream/StreamOperatorMemoryExecutor.java
core/src/main/java/cn/edu/tsinghua/iginx/engine/physical/memory/execute/utils/RowUtils.java
core/src/main/java/cn/edu/tsinghua/iginx/sql/IginXSqlVisitor.java
core/src/test/java/cn/edu/tsinghua/iginx/engine/physical/memory/execute/AbstractOperatorMemoryExecutorTest.java
test/src/test/java/cn/edu/tsinghua/iginx/integration/SQLSessionIT.java

1. dev stream join
2. fix some bugs
3. add some UTs and ITs

dev stream join

---

.github/workflows/capacity-expansion.yml
core/src/main/java/cn/edu/tsinghua/iginx/IginxWorker.java
core/src/main/java/cn/edu/tsinghua/iginx/engine/logical/generator/QueryGenerator.java
core/src/main/java/cn/edu/tsinghua/iginx/engine/logical/optimizer/FilterFragmentOptimizer.java
core/src/main/java/cn/edu/tsinghua/iginx/metadata/DefaultMetaManager.java
core/src/main/java/cn/edu/tsinghua/iginx/metadata/IMetaManager.java
core/src/main/java/cn/edu/tsinghua/iginx/metadata/cache/DefaultMetaCache.java
core/src/main/java/cn/edu/tsinghua/iginx/metadata/cache/IMetaCache.java
core/src/main/java/cn/edu/tsinghua/iginx/metadata/entity/FragmentMeta.java
core/src/main/java/cn/edu/tsinghua/iginx/metadata/entity/StorageEngineMeta.java
core/src/main/java/cn/edu/tsinghua/iginx/metadata/entity/StorageUnitMeta.java
core/src/main/java/cn/edu/tsinghua/iginx/metadata/storage/IMetaStorage.java
core/src/main/java/cn/edu/tsinghua/iginx/metadata/storage/etcd/ETCDMetaStorage.java
core/src/main/java/cn/edu/tsinghua/iginx/metadata/storage/zk/ZooKeeperMetaStorage.java
session/src/main/java/cn/edu/tsinghua/iginx/session/Session.java
test/src/test/java/cn/edu/tsinghua/iginx/integration/expansion/iotdb/IoTDBHistoryDataCapacityExpansionIT.java
thrift/src/main/proto/rpc.thrift

Remove history data
